version: '3.8'

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - lamp-net

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vuln0
      MYSQL_USER: vuln0
      MYSQL_PASSWORD: vuln0
    ports:
      - "3306:3306"
    volumes:
      - ./_docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - lamp-net

networks:
  lamp-net:
    driver: bridge
