version: '3.8'

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"     # 웹용
      - "2222:22"     # SSH용
    volumes:
      - ./web:/var/www/html                                # 실습 전용 영역만 마운트
    depends_on:
      - db
    networks:
      - lamp-net

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vuln1
      MYSQL_USER: vuln1
      MYSQL_PASSWORD: vuln1
    ports:
      - "3306:3306"
    volumes:
      - ./_docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - lamp-net

networks:
  lamp-net:
    driver: bridge
